name: Windows

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: [x86, x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - name: Install Npcap
        run: |
          Invoke-WebRequest https://npcap.com/dist/npcap-sdk-1.13.zip -OutFile ../npcap-sdk.zip
          Expand-Archive ../npcap-sdk.zip -DestinationPath ../npcap-sdk
      - name: Build ${{ matrix.arch }}
        shell: cmd
        run: |
          .\win32\msvcbuild.bat ${{ matrix.arch }}
      - name: Archive DLL files
        uses: actions/upload-artifact@v3
        with:
          name: libnet-${{ matrix.arch }}-build${{ github.run_number }}
          path: lib/${{ matrix.arch }}
